# generated by scripts/generate_models.py
#   source: data/un-api-openapi.json

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class ApiDisaggregatedDimenions(BaseModel):
    id: str | None = None
    goal: int | None = None
    target: str | None = None
    indicator: str | None = None
    seriesCode: str | None = None
    disaggregatedCategory: str | None = None


class ApiOneSeriesMultiArea(BaseModel):
    indicator: str | None = None
    seriesCode: str | None = None
    seriesTitle: str | None = None
    disaggregationType: str | None = None
    units: str | None = None
    countryData: list[ApiCountrywiseData] | None = None


class ApiCountrywiseData(BaseModel):
    geoAreaCode: str | None = None
    geoAreaName: str | None = None
    chartColor: str | None = None
    yearWiseData: list[ApiYearWiseData] | None = None


class ApiYearWiseData(BaseModel):
    year: str | None = None
    value: str | None = None


class ApiMultiSeriesOneArea(BaseModel):
    geoAreaCode: str | None = None
    geoAreaName: str | None = None
    ctSeriesWiseData: list[ApiSeriesData] | None = None


class ApiSeriesData(BaseModel):
    indicator: str | None = None
    seriesCode: str | None = None
    seriesTitle: str | None = None
    disaggregationType: str | None = None
    units: str | None = None
    chartColor: str | None = None
    yearWiseData: list[ApiYearWiseData] | None = None


class ApiCompareIndicatorsAcrossCountries(BaseModel):
    goalId: str | None = None
    goalName: str | None = None
    indicators: list[ApiIndicatorPercentage] | None = None


class ApiIndicatorPercentage(BaseModel):
    code: str | None = None
    description: str | None = None
    percentage: str | None = None


class ApiCountriesAcrossAllGoals(BaseModel):
    goals: list[SDGGoals] | None = None
    goalsCountryDetails: list[GoalsCountrywiseData] | None = None


class SDGGoals(BaseModel):
    goalId: int | None = None
    goalName: str | None = None


class GoalsCountrywiseData(BaseModel):
    geoAreaCode: int | None = None
    geoAreaName: str | None = None
    goal1: float | None = None
    goal2: float | None = None
    goal3: float | None = None
    goal4: float | None = None
    goal5: float | None = None
    goal6: float | None = None
    goal7: float | None = None
    goal8: float | None = None
    goal9: float | None = None
    goal10: float | None = None
    goal11: float | None = None
    goal12: float | None = None
    goal13: float | None = None
    goal14: float | None = None
    goal15: float | None = None
    goal16: float | None = None
    goal17: float | None = None


class ApiGeoArea(BaseModel):
    geoAreaCode: str | None = Field(None, description="geoAreaCode is equivalent to M49")
    geoAreaName: str | None = Field(
        None, description="geoArea Name is the offician UN name for that country or region."
    )


class ApiGeoTree(BaseModel):
    geoAreaCode: int | None = Field(None, description="Gets or Sets code")
    geoAreaName: str | None = Field(None, description="Gets or Sets name")
    type: str | None = Field(None, description="Gets or Sets type")
    children: list[ApiGeoTree] | None = Field(None, description="Gets or Sets children")


class ApiGoalData(BaseModel):
    code: str | None = Field(None, description="Gets or Sets Code")
    title: str | None = Field(None, description="Gets or Sets Title")
    description: str | None = Field(None, description="Gets or Sets Description")
    uri: str | None = Field(None, description="Gets or Sets URI")
    targets: list[ApiTargetData] | None = Field(None, description="Gets or Sets Targets")


class ApiTargetData(BaseModel):
    code: str | None = Field(None, description="Gets or Sets Code")
    title: str | None = Field(None, description="Gets or Sets Title")
    description: str | None = Field(None, description="Gets or Sets Description")
    URI: str | None = Field(None, description="Gets or Sets URI")
    indicators: list[ApiIndicatorData] | None = Field(None, description="Gets or Sets Indicators")


class ApiIndicatorData(BaseModel):
    code: str | None = Field(None, description="Gets or Sets Code")
    description: str | None = Field(None, description="Gets or Sets Description")
    tier: str | None = Field(None, description="Gets or Sets Tier")
    uri: str | None = Field(None, description="Gets or Sets URI")
    series: list[ApiSerieData] | None = Field(None, description="Gets or Sets Series")


class ApiSerieData(BaseModel):
    release: str | None = Field(None, description="Gets or Sets Series")
    code: str | None = None
    description: str | None = Field(None, description="Gets or Sets Description")
    uri: str | None = Field(None, description="Gets or Sets URI")
    observations: list[ApiObservation] | None = Field(None, description="Gets or Sets attributes")


class ApiObservation(BaseModel):
    goal: list[str] | None = Field(None, description="Gets or Sets Goal")
    target: list[str] | None = Field(None, description="Gets or Sets Target")
    indicator: list[str] | None = Field(None, description="Gets or Sets Indicator")
    series: str | None = Field(None, description="Gets or Sets Series")
    seriesDescription: str | None = Field(None, description="Gets or Sets Series Description")
    seriesCount: str | None = Field(None, description="Gets or Sets Series Count")
    geoAreaCode: str | None = Field(None, description="Gets or Sets geoAreaCode")
    geoAreaName: str | None = Field(None, description="Gets or Sets geoAreaName")
    timePeriodStart: float | None = Field(None, description="Gets or Sets timePeriod Start")
    value: str | None = Field(None, description="Gets or Sets Value")
    valueType: str | None = Field(None, description="Gets or Sets ValueType")
    time_detail: str | None = Field(None, description="Gets or Sets TimeDetail")
    timeCoverage: str | None = Field(None, description="Gets or Sets TimeCoverage")
    upperBound: str | None = Field(None, description="Gets or Sets UpperBound")
    lowerBound: str | None = Field(None, description="Gets or Sets LowerBound")
    basePeriod: str | None = Field(None, description="Gets or Sets BasePeriod")
    source: str | None = Field(None, description="Gets or Sets Source")
    geoInfoUrl: str | None = Field(None, description="Gets or Sets GeoInfoUrl")
    footnotes: list[str] | None = Field(None, description="Gets or Sets Footnotes")
    attributes: dict[str, str] | None = Field(None, description="Gets or Sets Attributes")
    dimensions: dict[str, str] | None = Field(None, description="Gets or Sets Dimensions")


class ApiGoal(BaseModel):
    code: str | None = Field(None, description="Gets or Sets Code")
    title: str | None = Field(None, description="Gets or Sets Title")
    description: str | None = Field(None, description="Gets or Sets Description")
    uri: str | None = Field(None, description="Gets or Sets URI")
    targets: list[ApiTarget] | None = Field(None, description="Gets or Sets Targets")


class ApiTarget(BaseModel):
    goal: str | None = Field(None, description="Gets or Sets Code")
    code: str | None = Field(None, description="Gets or Sets Code")
    title: str | None = Field(None, description="Gets or Sets Title")
    description: str | None = Field(None, description="Gets or Sets Description")
    uri: str | None = Field(None, description="Gets or Sets URI")
    indicators: list[ApiIndicator] | None = Field(None, description="Gets or Sets Indicators")


class ApiIndicator(BaseModel):
    goal: str | None = Field(None, description="Gets or Sets Goal")
    target: str | None = Field(None, description="Gets or Sets Code")
    code: str | None = Field(None, description="Gets or Sets Code")
    description: str | None = Field(None, description="Gets or Sets Description")
    tier: str | None = Field(None, description="Gets or Sets Tier")
    uri: str | None = Field(None, description="Gets or Sets URI")
    series: list[ApiSerie] | None = Field(None, description="Gets or Sets Series")


class ApiSerie(BaseModel):
    goal: list[str] | None = Field(None, description="Gets or Sets Goal")
    target: list[str] | None = Field(None, description="Gets or Sets Target")
    indicator: list[str] | None = Field(None, description="Gets or Sets Indicator")
    release: str | None = Field(None, description="Gets or Sets Release")
    code: str | None = Field(None, description="Gets or Sets Code")
    description: str | None = Field(None, description="Gets or Sets Description")
    uri: str | None = Field(None, description="Gets or Sets URI")


class ApiDimension(BaseModel):
    id: str | None = Field(None, description="Gets or Sets id")
    codes: list[ApiCodeList] | None = Field(None, description="Gets or Sets codeList")


class ApiCodeList(BaseModel):
    code: str | None = Field(None, description="Gets or Sets code")
    description: str | None = Field(None, description="Gets or Sets code")
    sdmx: str | None = Field(None, description="Gets or Sets code")


class ApiObservationPage(BaseModel):
    size: int | None = Field(
        None, description="Gets or Sets Size\r\nThe number of elements in the page"
    )
    totalElements: int | None = Field(
        None, description="Gets or Sets TotalElements\r\nThe total number of elements"
    )
    totalPages: int | None = Field(
        None, description="Gets or Sets totalPages\r\nThe total number of pages"
    )
    pageNumber: int | None = Field(
        None, description="Gets or Sets pageNumber\r\nThe current page number"
    )
    attributes: list[ApiDimension] | None = Field(None, description="Gets or Sets attributes")
    dimensions: list[ApiDimension] | None = Field(None, description="Gets or Sets dimensions")
    data: list[ApiObservation] | None = Field(None, description="Gets or Sets data")


class FileStreamResult(BaseModel):
    fileStream: Stream | None = None
    contentType: str | None = None
    fileDownloadName: str | None = None
    lastModified: datetime | None = None
    entityTag: EntityTagHeaderValue | None = None


class Stream(BaseModel):
    canRead: bool | None = None
    canSeek: bool | None = None
    canTimeout: bool | None = None
    canWrite: bool | None = None
    length: int | None = None
    position: int | None = None
    readTimeout: int | None = None
    writeTimeout: int | None = None


class EntityTagHeaderValue(BaseModel):
    tag: StringSegment | None = None
    isWeak: bool | None = None


class StringSegment(BaseModel):
    buffer: str | None = None
    offset: int | None = None
    length: int | None = None
    value: str | None = None
    hasValue: bool | None = None


class ApiObservationPivotPage(BaseModel):
    size: int | None = Field(
        None, description="Gets or Sets Size\r\nThe number of elements in the page"
    )
    totalElements: int | None = Field(
        None, description="Gets or Sets TotalElements\r\nThe total number of elements"
    )
    totalPages: int | None = Field(
        None, description="Gets or Sets totalPages\r\nThe total number of pages"
    )
    pageNumber: int | None = Field(
        None, description="Gets or Sets pageNumber\r\nThe current page number"
    )
    attributes: list[ApiDimension] | None = Field(None, description="Gets or Sets attributes")
    dimensions: list[ApiDimension] | None = Field(None, description="Gets or Sets dimensions")
    data: list[ApiObservationPivot] | None = Field(None, description="Gets or Sets data")


class ApiObservationPivot(BaseModel):
    goal: str | None = Field(None, description="Gets or Sets Goal")
    target: str | None = Field(None, description="Gets or Sets Target")
    indicator: str | None = Field(None, description="Gets or Sets Indicator")
    series: str | None = Field(None, description="Gets or Sets Series")
    seriesDescription: str | None = Field(None, description="Gets or Sets Series")
    seriesCount: str | None = Field(None, description="Gets or Sets Series")
    geoAreaCode: str | None = Field(None, description="Gets or Sets geoAreaCode")
    geoAreaName: str | None = Field(None, description="Gets or Sets geoAreaName")
    timeCoverage: str | None = Field(None, description="Gets or Sets TimeCoverage")
    upperBound: str | None = Field(None, description="Gets or Sets UpperBound")
    lowerBound: str | None = Field(None, description="Gets or Sets LowerBound")
    basePeriod: str | None = Field(None, description="Gets or Sets BasePeriod")
    source: str | None = Field(None, description="Gets or Sets Source")
    geoInfoUrl: str | None = Field(None, description="Gets or Sets GeoInfoUrl")
    age: str | None = Field(None, description="Gets or Sets age")
    freq: str | None = Field(None, description="Gets or Sets freq")
    sex: str | None = Field(None, description="Gets or Sets sex")
    location: str | None = Field(None, description="Gets or Sets location")
    units: str | None = Field(None, description="Gets or Sets Units")
    level_status: str | None = Field(None, description="Gets or Sets level/status")
    name_of_international_agreement: str | None = Field(
        None, description="Gets or Sets name of international agreement"
    )
    education_level: str | None = Field(None, description="Gets or Sets education level")
    type_of_product: str | None = Field(None, description="Gets or Sets type of product")
    type_of_facilities: str | None = Field(None, description="Gets or Sets type of facilities")
    name_of_international_institution: str | None = Field(
        None, description="Gets or Sets name of international institution"
    )
    type_of_occupation: str | None = Field(None, description="Gets or Sets type of occupation")
    tariff_regime_status: str | None = Field(None, description="Gets or Sets tariff regime status")
    mode_of_transportation: str | None = Field(
        None, description="Gets or Sets mode of transportation"
    )
    type_of_mobile_technology: str | None = Field(
        None, description="Gets or Sets type of mobile technology"
    )
    name_of_non_communicable_disease: str | None = Field(
        None, description="Gets or Sets name of non-communicable disease"
    )
    type_of_skill: str | None = Field(None, description="Gets or Sets type of skill")
    type_of_speed: str | None = Field(None, description="Gets or Sets type of speed")
    migratory_status: str | None = Field(None, description="Gets or Sets migratory status")
    disability_status: str | None = Field(None, description="Gets or Sets disability status")
    hazard_type: str | None = Field(None, description="Gets or Sets hazard type")
    ihr_capacity: str | None = Field(None, description="Gets or Sets ihr capacity")
    reporting_type: str | None = Field(None, description="Gets or Sets Units")
    cities: str | None = Field(None, description="Gets or Sets cities")
    activity: str | None = Field(None, description="Gets or Sets Activity")
    policy_domains: str | None = Field(None, description="Gets or Sets Policy Domains")
    years: str | None = Field(None, description="Gets or Sets years")


class SDMXMetaDataResponse(BaseModel):
    series: str | None = None
    seriesDesc: str | None = None
    indicatorDesc: str | None = None
    conceptId: str | None = None
    conceptName: str | None = None
    conceptDesc: str | None = None
    conceptHTML: str | None = None
    parentId: str | None = None


class ConceptsMasterData(BaseModel):
    conceptId: str | None = None
    conceptName: str | None = None
    parentId: str | None = None


class ApiSliceData(BaseModel):
    series: str | None = Field(None, description="Gets or Sets Series")
    geoAreaCode: int | None = Field(None, description="Gets or Sets geoAreaCode")
    geoAreaName: str | None = Field(None, description="Gets or Sets geoAreaName")
    dimensions: list[dict[str, str]] | None = Field(
        None, description="Gets or Sets Dimensions for slice data"
    )


class FileResult(BaseModel):
    contentType: str | None = None
    fileDownloadName: str | None = None
    lastModified: datetime | None = None
    entityTag: EntityTagHeaderValue | None = None


ApiGeoTree.model_rebuild()
