#!/usr/bin/env python3
"""Regenerate sdgdata models from the committed OpenAPI document."""

from __future__ import annotations

import argparse
import filecmp
import json
import keyword
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "data" / "un-api-openapi.json"
COMMITTED_OPENAPI_CLIENT = ROOT / "generated" / "openapi_python_client"
COMMITTED_MODELS = ROOT / "src" / "sdgdata" / "models.py"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate committed OpenAPI client model output and Pydantic compatibility models."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare regenerated output with committed files without changing them.",
    )
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="sdgdata-models-") as tmp:
        tmp_path = Path(tmp)
        generated_client = tmp_path / "openapi_python_client"
        generated_models = tmp_path / "models.py"

        run_openapi_python_client(generated_client)
        normalize_openapi_client_output(generated_client)
        generated_models.write_text(render_pydantic_models(), encoding="utf-8")
        format_python_file(generated_models)

        if args.check:
            return check_generated_files(generated_client, generated_models)

        replace_tree(generated_client, COMMITTED_OPENAPI_CLIENT)
        COMMITTED_MODELS.write_text(generated_models.read_text(encoding="utf-8"), encoding="utf-8")

    print("Regenerated OpenAPI model artifacts.")
    return 0


def run_openapi_python_client(output_path: Path) -> None:
    subprocess.run(
        [
            sys.executable,
            "-m",
            "openapi_python_client",
            "generate",
            "--path",
            str(OPENAPI_PATH),
            "--meta",
            "none",
            "--output-path",
            str(output_path),
            "--overwrite",
        ],
        cwd=ROOT,
        check=True,
    )


def normalize_openapi_client_output(output_path: Path) -> None:
    """Keep only deterministic, model-related generated files for review."""
    for relative_path in ("api", ".ruff_cache", "client.py", "errors.py", "__init__.py"):
        path = output_path / relative_path
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()


def format_python_file(path: Path) -> None:
    subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", "--exit-zero", "--quiet", str(path)],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    subprocess.run(
        [sys.executable, "-m", "ruff", "format", str(path)],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def render_pydantic_models() -> str:
    schemas = load_schemas()
    class_names = set(schemas)
    classes = [render_class(name, schema, class_names) for name, schema in schemas.items()]
    rebuilds = [
        f"{name}.model_rebuild()"
        for name, schema in schemas.items()
        if schema_references(schema, name)
    ]

    parts = [
        "# generated by scripts/generate_models.py",
        "#   source: data/un-api-openapi.json",
        "",
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from typing import Any, Dict, List, Optional",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "",
        "\n\n".join(classes),
    ]
    if rebuilds:
        parts.extend(["", "", "\n".join(rebuilds)])
    return "\n".join(parts) + "\n"


def load_schemas() -> dict[str, dict[str, Any]]:
    spec = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    return spec["components"]["schemas"]


def render_class(name: str, schema: dict[str, Any], class_names: set[str]) -> str:
    properties = schema.get("properties", {})
    lines = [f"class {name}(BaseModel):"]
    if not properties:
        lines.append("    pass")
        return "\n".join(lines)

    for property_name, property_schema in properties.items():
        field_name = python_identifier(property_name)
        annotation = f"Optional[{type_annotation(property_schema, class_names)}]"
        description = property_schema.get("description")
        field = f"Field(None, description={description!r})" if description else "None"
        if field_name != property_name:
            if description:
                field = f"Field(None, alias={property_name!r}, description={description!r})"
            else:
                field = f"Field(None, alias={property_name!r})"
        lines.append(f"    {field_name}: {annotation} = {field}")

    return "\n".join(lines)


def type_annotation(schema: dict[str, Any], class_names: set[str]) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[1]
        return name if name in class_names else "Any"

    if schema.get("allOf"):
        return type_annotation(schema["allOf"][0], class_names)

    schema_type = schema.get("type")
    schema_format = schema.get("format")

    if schema_type == "array":
        return f"List[{type_annotation(schema.get('items', {}), class_names)}]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Dict[str, {type_annotation(additional, class_names)}]"
        return "Dict[str, Any]"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "string" and schema_format == "date-time":
        return "datetime"
    if schema_type == "string":
        return "str"
    return "Any"


def python_identifier(value: str) -> str:
    candidate = re.sub(r"\W+", "_", value).strip("_")
    if not candidate:
        candidate = "field"
    if candidate[0].isdigit():
        candidate = f"field_{candidate}"
    if keyword.iskeyword(candidate):
        candidate = f"{candidate}_"
    return candidate


def schema_references(schema: dict[str, Any], name: str) -> bool:
    if isinstance(schema, dict):
        if schema.get("$ref") == f"#/components/schemas/{name}":
            return True
        return any(schema_references(value, name) for value in schema.values())
    if isinstance(schema, list):
        return any(schema_references(item, name) for item in schema)
    return False


def check_generated_files(generated_client: Path, generated_models: Path) -> int:
    stale = False
    if not directories_match(generated_client, COMMITTED_OPENAPI_CLIENT):
        relative_client = COMMITTED_OPENAPI_CLIENT.relative_to(ROOT)
        print(
            f"Generated OpenAPI client models are stale: {relative_client}",
            file=sys.stderr,
        )
        stale = True

    if not files_match(generated_models, COMMITTED_MODELS):
        print(
            f"Generated Pydantic models are stale: {COMMITTED_MODELS.relative_to(ROOT)}",
            file=sys.stderr,
        )
        stale = True

    if stale:
        print("Run: uv run python scripts/generate_models.py", file=sys.stderr)
        return 1

    print("Generated models are current.")
    return 0


def directories_match(left: Path, right: Path) -> bool:
    if not right.exists():
        return False
    comparison = filecmp.dircmp(left, right)
    if (
        comparison.left_only
        or comparison.right_only
        or comparison.diff_files
        or comparison.funny_files
    ):
        return False
    return all(directories_match(left / name, right / name) for name in comparison.common_dirs)


def files_match(left: Path, right: Path) -> bool:
    return right.exists() and left.read_bytes() == right.read_bytes()


def replace_tree(source: Path, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


if __name__ == "__main__":
    raise SystemExit(main())
